version: '1.0'

services:
  redis:
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379"
      
  django:
    container_name: django
    build:
      context: ./mycelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mycelery:/usr/src/app/
    ports:
      - 8001:8000
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./mycelery
    command: celery --app=mycelery worker -l INFO
    volumes:
      - ./mycelery:/usr/src/app/
    depends_on:
      - redis